#!/bin/bash
#
#  Deletes files older than 90 days from
#  all user's directories on /sciclone/scr20
#

dry_run="no"
#retrieve users
users=`awk -F: '{print $1}' /etc/passwd | sort`
Age=90

for i in $users
do
        Scr="/sciclone/scr20/$i"
        #if the directory exists and the user is not root
        if [[ -d $Scr && $i != "root" ]] ; then
                echo $Scr
                #first comment is the one we need to uncomment
                if [[ "$dry_run" -eq "yes" ]]; then
                        /bin/find $Scr -mount -type f -atime +$Age -exec ls -lu "{}" \        
                elif [[ "$dry_run" -eq "no" ]]; then
                        /bin/find $Scr -mount -type f -atime +$Age -print -exec /bin/rm -f {} \;
                fi
        fi
done

exit 0
